### ISSUE TITLE
undefined is not a function: MailCore.loginSmtp

### ISSUE THREAD

**Issue by robinalexandre** [agenthunt/react-native-mailcore#13]
Hi there,

First, thanks for this library.
When I follow the README, I add mailcore2-ios in the podfile then `pod install`. I can see that mailcore2 is well installed in Xcode. However, when I do `pod install`, it keep telling me `[!] use_native_modules! skipped the react-native dependency 'react-native-mailcore'. No podspec file was found.` and if I try to use loginSmtp or any other function, it tells me it's undefined.

Any idea ?

Thank you,
Alexandre

**Comment by robinalexandre** [comment]
I created a podspec and now everything is fine. You should add it in your code in the iOS folder of react-native-mailcore:

`require 'json'

package = JSON.parse(File.read(File.join(__dir__, "..", 'package.json')))

Pod::Spec.new do |s|
  s.name         = package['name']
  s.version      = package['version']
  s.summary      = package['description']
  s.license      = package['license']

  s.authors      = package['author']
  s.homepage     = package['homepage']
  s.platform     = :ios, "9.0"

  s.source       = { :git => "git+https://github.com/agenthunt/react-native-mailcore.git", :tag => "v#{s.version}" }
  s.source_files  = "*.{h,m}"

  s.dependency 'React'
  s.dependency 'mailcore2-ios'
end`

**Comment by ninad458** [comment]
I'm getting the same error. Do I need to download the project, make changes in the project and build it locally?
