### ISSUE TITLE
sendMail functionality in react-native-mailcore fails when i am trying to reply the same mail

### ISSUE THREAD

**Issue by ashishdevadiga** [agenthunt/react-native-mailcore#17]
> sendMail functionality in react-native-mailcore works fine,  when i am send a new mail, Application is crashing While i am trying to reply the same mail, please consider this issue and give me reply as soon as possible because i am wasting a lot time with this thank you!

**Comment by agenthunt** [comment]
Thanks for the message @ashishdevadiga . Unfortunately haven't had time to look into the project recently. However if you could provide more details about your crash by providing sample application or a stack trace or any other details, it would help us or anyone to point out what could be wrong

**Comment by ashishdevadiga** [comment]
@agenthunt  Thank you for your reply, I am getting a crash in MessageHeader inside sendMail functionality so I have changed to MessageBuilder this works fine for me.
