### ISSUE TITLE
MailCore.h file not found in iOS

### ISSUE THREAD

**Issue by Selvamhibiz** [agenthunt/react-native-mailcore#3]
Hi,

I am using XCode version 9.2.  I am unable to run my react native iOS project after installing mail core npm. It fails building the app and shows "MailCore/MailCore.h" file not found. Any body faced this issue earlier. Need help on how to fix this issue.

**Comment by agenthunt** [comment]
Hi @Selvamhibiz ,
Have you run the pod setup as mentioned in the README ?

**Comment by Selvamhibiz** [comment]
Hi,

I can able to send email from iOS. But when i try to run in android its throwing me an error stating "node_modules\react-native-mailcore\android\src\main\java\com\reactlib
rary\RNMailCorePackage.java:19: error: method does not override or implement a m
ethod from a supertype
    @Override
    ^
Note: Recompile with -Xlint:unchecked for details.
"

I have changed my react native version in to 0.51.0 in build.gradle file

**Comment by agenthunt** [comment]
Is there still a problem with android ?

**Comment by agenthunt** [comment]
Fixed in 0.0.2
